---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

#verifier:
#  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
       gui: true
       customize:
          memory: 4048
suites:
  - name: default
    run_list:
     - recipe[maven::default]
     - recipe[dev2::git]     
     - role[java] # todo install java 7
     - recipe[google-chrome::default]
     - recipe[sublime-text::default]    
     - recipe[ruby-install::default]
     - recipe[dev2::gnome]
     - recipe[nodejs::default]   
     - recipe[nodejs::npm]             
     
     # todo ruby 
     #- recipe[dev2::idea]
    #verifier:
    #  inspec_tests:
    #    - test/smoke/default
    #attributes:
